# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Martin's CindyJS Blog
subtitle: Martin's Blog
email: gagern@ma.tum.de
description: > # this means to ignore newlines until "baseurl:"
  Mathematical content and examples by Martin von Gagern using CindyJS.
baseurl: "/CindyJS" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username: gagern
repository: gagern/CindyJS
gh:
  repo:   gagern/CindyJS
  branch: gh-pages
license:
  name: CC-BY-SA 4.0 License
  url:  http://creativecommons.org/licenses/by-sa/4.0/
  icon: https://i.creativecommons.org/l/by-sa/4.0/88x31.png

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
